rvm:
  - 2.0.0
  - 2.1.5
  - 2.2.0

services:
  - mysql
#  - mongodb

before_script:
  - mysql -e 'create database archive_catalog_test;' -uroot
#  - mysql -e 'create database myapp_test;'

install: ./bin/setup.sh

script: ./bin/test.sh


