rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.5
  - 2.2.0

install:
  - bundle install --binstubs .binstubs --clean --jobs=3 --retry=3 --without=integration, staging, production
  - bundle show --paths

script: ./bin/test.sh


