# Oracle/OCI 8i, 9, 10g
#
# Requires Ruby/OCI8:
#  http://rubyforge.org/projects/ruby-oci8/
#
# Specify your database using any valid connection syntax, such as a
# tnsnames.ora service name, or an SQL connect string of the form:
#
#   //host:[port][/service name]
#
# By default prefetch_rows (OCI_ATTR_PREFETCH_ROWS) is set to 100. And
# until true bind variables are supported, cursor_sharing is set by default
# to 'similar'. Both can be changed in the configuration below; the defaults
# are equivalent to specifying:
#
#  prefetch_rows: 100
#  cursor_sharing: similar


# Trouble shooting db schema definitions, see
# http://stackoverflow.com/questions/250545/schema-dump-on-legacy-oracle-database-using-dbschemadump-using-rake
# http://guides.rubyonrails.org/migrations.html#schema-dumping-and-you
# http://stackoverflow.com/questions/8201572/multicolumn-primary-keys-in-rails


# Environments here are related to ENV['APP_ENV'], not ENV['RACK_ENV']
# The APP_ENV should be set in a .env file on the developer or deployed system.


# Warning: The "test" database will be erased and
# re-generated from your development database when you run "rake".
# Do not set this db to the same as development or production.
test:
  adapter: mysql
  host: localhost
  port: 3306
  database: archive_catalog_test
  user: sdrAdmin
  password: sdrPass

# local is for developer workstations
local:
  adapter: mysql
  host: localhost
  port: 3306
  database: archive_catalog_development
  user: sdrAdmin
  password: sdrPass


